global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "alert.rules"

scrape_configs:
  - job_name: 'streamprocess-api'
    static_configs:
      - targets: ['api:9090']
    metrics_path: '/metrics'

  - job_name: 'streamprocess-worker'
    static_configs:
      - targets: ['worker:9090']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
